services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: monitoramento
      POSTGRES_PASSWORD: monitoramento
      POSTGRES_DB: monitoramento_saude
    ports:
      - "6543:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U monitoramento -d monitoramento_saude"]
      interval: 5s
      timeout: 5s
      retries: 20

  flyway:
    image: flyway/flyway:10
    command: -connectRetries=60 migrate
    environment:
      FLYWAY_URL: jdbc:postgresql://db:5432/monitoramento_saude
      FLYWAY_USER: monitoramento
      FLYWAY_PASSWORD: monitoramento
      FLYWAY_SCHEMAS: monitoramento
      FLYWAY_BASELINE_ON_MIGRATE: "true"
    volumes:
      - ./db/migration:/flyway/sql:ro
    depends_on:
      db:
        condition: service_healthy

  api:
    build: .
    environment:
      ENV: dev
      GUNICORN_WORKERS: 2
      DATABASE_URL: postgresql+psycopg://monitoramento:monitoramento@db:5432/monitoramento_saude
      # Configurações da API
      API_KEYS: this-is-a-sample-api-key
      API_SECRET: change-me
      REQUIRE_HMAC: "false"
      ALLOWED_ORIGINS: http://localhost:8000
      ENFORCE_ORIGIN_CHECK: "false"
    ports:
      - "8000:8000"
    depends_on:
      flyway:
        condition: service_completed_successfully

volumes:
  postgres_data:
